version: '3.8'

services:
  api:
    build: .
    container_name: api
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./videos:/app/videos
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker
    command: ["python", "worker.py"]
    volumes:
      - ./videos:/app/videos
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

